services:
  client:
    image: node:18
    working_dir: /client
    volumes:
      - ./client:/client
    # Added --port needed for vite to start server on port 80 and --host is for hosting the app on network
    command: sh -c "npm install && npm run dev -- --host --port 80"

  server:
    image: node:18
    working_dir: /server
    environment:
      - PORT=80
    volumes:
      - ./server:/server
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server
